# Generated by Django 4.1.2 on 2022-10-10 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Michael Dsouza', max_length=255)),
                ('address', models.TextField(default='Shop No.1, Rosy Apartment, Cabin Road, Bhayander(west), Mumbai-401106')),
                ('phone', models.IntegerField(default='+91 9876543210')),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 10, 14, 25, 0, 972634))),
            ],
        ),
    ]
