# Generated by Django 4.1.2 on 2022-10-10 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('purchased_date', models.DateTimeField(default=datetime.datetime(2022, 10, 10, 14, 45, 40, 861763))),
            ],
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 10, 14, 45, 40, 860766)),
        ),
    ]
