# Generated by Django 4.1.2 on 2022-10-10 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buyer_alter_seller_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.ImageField(upload_to='media/')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_desc', models.TextField()),
                ('prod_price', models.IntegerField()),
                ('prod_ratings', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='buyer',
            name='purchased_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 14, 51, 36, 213148)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 10, 14, 51, 36, 213149)),
        ),
    ]
